# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('company', '0002_auto_20190110_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterfeit_prodect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('number', models.IntegerField(verbose_name='防伪数量')),
                ('epoch', models.DateField(verbose_name='假冒出现时间')),
                ('site', models.CharField(max_length=50, verbose_name='出现地点')),
                ('c_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='假冒产品')),
            ],
            options={
                'verbose_name': '防伪监管',
                'verbose_name_plural': '防伪监管',
            },
        ),
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('logistics', models.IntegerField(verbose_name='物流码')),
                ('information', models.BooleanField(choices=[(0, '真'), (1, '假')], default=0, verbose_name='防伪溯源信息')),
                ('query_type', models.CharField(max_length=20, verbose_name='查询类型')),
                ('query_time', models.DateField(verbose_name='查询时间')),
                ('query_site', models.CharField(max_length=50, verbose_name='查询地点')),
                ('query_id', models.IntegerField(verbose_name='查询id')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='产品类别')),
                ('real_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='生产企业')),
                ('real_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='生产日期')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
