# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '企业信息', 'verbose_name_plural': '企业信息'},
        ),
    ]
