# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190108_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_document',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='企业证件'),
        ),
        migrations.AlterField(
            model_name='company',
            name='c_name',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='company',
            name='c_status',
            field=models.SmallIntegerField(blank=True, choices=[(1, '提交,待审核'), (2, '审核通过'), (3, '审核拒绝')], default='', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='company',
            name='c_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyType', verbose_name='企业类型'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.City', verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='company',
            name='credit_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='信用代码'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='法人姓名'),
        ),
        migrations.AlterField(
            model_name='company',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Province', verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='注册地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='用户名'),
        ),
    ]
