# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_product',
            field=models.BooleanField(default=False),
        ),
    ]
