# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('cate_name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('p_name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('p_type', models.CharField(max_length=20, verbose_name='产品类型')),
                ('company', models.CharField(max_length=50, verbose_name='生产厂商')),
                ('p_standard', models.CharField(max_length=20, verbose_name='产品规格')),
                ('p_date', models.DateTimeField(verbose_name='生产日期')),
                ('p_period', models.CharField(max_length=20, verbose_name='保质期')),
                ('p_place', models.CharField(max_length=20, verbose_name='产地')),
                ('anti_fake_logo', models.CharField(default='logo', max_length=20, verbose_name='防伪标识')),
                ('p_status', models.BooleanField(choices=[(0, '初始化'), (1, '提交申请'), (2, '生产防伪码')], default=0, verbose_name='状态')),
                ('p_feature', models.CharField(blank=True, max_length=250, null=True, verbose_name='特色')),
                ('p_operate', models.CharField(blank=True, max_length=250, null=True, verbose_name='生产工艺')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '产品详情',
                'verbose_name_plural': '产品详情',
            },
        ),
    ]
